-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS `USERS` (
    `USR_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'USER ID',
    `USR_EMAIL` VARCHAR(30) NOT NULL DEFAULT '' COMMENT 'EMAIL',
    `USR_PHONE` VARCHAR(15) NOT NULL DEFAULT '' COMMENT 'PHONE NUMBER',
    `USR_USERNAME` VARCHAR(30) NOT NULL DEFAULT '' COMMENT 'USERNAME',
    `USR_PASSWORD` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'PASSWORD',
    `USR_CREATED_AT` INT(11) NOT NULL DEFAULT '0' COMMENT 'CREATED TIME',
    `USR_UPDATED_AT` INT(11) NOT NULL DEFAULT '0' COMMENT 'UPDATED TIME',
    `USR_CREATE_IP_AT` VARCHAR(12) NOT NULL DEFAULT '' COMMENT 'CREATION IP',
    `USR_LAST_LOGIN_AT` INT(11) NOT NULL DEFAULT '0' COMMENT 'LAST LOGIN TIME',
    `USR_LAST_LOGIN_IP_AT` VARCHAR(12) NOT NULL DEFAULT '' COMMENT 'LAST LOGIN IP',
    `USR_LOGIN_TIMES` INT(11) NOT NULL DEFAULT '0' COMMENT 'LOGIN TIMES',
    `USR_STATUS` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'STATUS 1:ENABLE 0:DISABLE -1:DELETE',
    PRIMARY KEY (`USR_ID`),
    KEY `IDX_USR_EMAIL` (`USR_EMAIL`),
    KEY `IDX_USR_PHONE` (`USR_PHONE`),
    KEY `IDX_USR_USERNAME` (`USR_USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='USERS';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS `USERS`;
-- +goose StatementEnd
