server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: 33306
  username: root
  password: root1234
  dbname: book-shop
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
logger:
  logLevel: debug,
  fileLogName: "./storages/logs/dev.001.log"
  maxSize: 500
  maxBackups: 3
  maxAge: 28
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password:
  database: 0