version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: book-shop-mysql
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: book-shop
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d"

volumes:
  mysql-data:
