// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

// USERS
type User struct {
	// USER ID
	UsrID uint32
	// EMAIL
	UsrEmail string
	// PHONE NUMBER
	UsrPhone string
	// USERNAME
	UsrUsername string
	// PASSWORD
	UsrPassword string
	// CREATED TIME
	UsrCreatedAt int32
	// UPDATED TIME
	UsrUpdatedAt int32
	// CREATION IP
	UsrCreateIpAt string
	// LAST LOGIN TIME
	UsrLastLoginAt int32
	// LAST LOGIN IP
	UsrLastLoginIpAt string
	// LOGIN TIMES
	UsrLoginTimes int32
	// STATUS 1:ENABLE 0:DISABLE -1:DELETE
	UsrStatus bool
}
